FROM resin/rpi-raspbian

RUN apt-get update && apt-get install expect
COPY install_script /etc/postfix/install_script
RUN /etc/postfix/install_script

CMD postfix start

EXPOSE 25

CMD tail -f /dev/null