FROM resin/rpi-raspbian

# RUN apt-get update && apt-get install expect
# COPY install_script /etc/postfix/install_script
# ENV DEBIAN_FRONTEND interactive
# ENTRYPOINT set -v && /etc/postfix/install_script
# EXPOSE 25
# CMD postfix start && tail -f /dev/null

# Set params for postfix install
RUN apt update && apt install debconf
RUN debconf-set-selections <<< "postfix postfix/mailname string $(hostname -f)" && debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"

# Postfix install 
RUN apt update && apt install postfix postfix-mysql && apt install debconf

# Good for debugging
ENTRYPOINT apt install -y mutt dnsutils telnet nano curl

# Allow SMTP port to be visible
EXPOSE 25

# Start postfix server and leave the container running
CMD postfix start