FROM resin/rpi-raspbian

# RUN apt-get update && apt-get install expect
RUN apt update && apt install postfix
COPY install_script /etc/postfix/install_script
ENV DEBIAN_FRONTEND interactive
ENTRYPOINT set -v && /etc/postfix/install_script
EXPOSE 25
CMD postfix start && tail -f /dev/null