FROM resin/rpi-raspbian

# RUN apt-get update && apt-get install expect
# COPY install_script /etc/postfix/install_script
# ENV DEBIAN_FRONTEND interactive
# ENTRYPOINT set -v && /etc/postfix/install_script
# EXPOSE 25
# CMD postfix start && tail -f /dev/null

# Set params for postfix install
RUN apt update && apt install debconf
# RUN debconf-set-selections <<< "postfix postfix/mailname string $(hostname -f)" 
# RUN debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
RUN echo "postfix postfix/mailname string $(hostname -f)" | debconf-set-selections
RUN echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections

# Postfix install 
RUN apt update && apt install postfix postfix-mysql

# Good for debugging
# RUN curl http://www.nano-editor.org/dist/v2.4/nano-2.4.2.tar.gz > nano-2.4.2.tar.gz && tar -xzf nano-2.4.2.tar.gz && cd nano-2.4.2 && ./configure && make && sudo make install
# RUN NANO_VERSION="2.2.6" && curl -O http://www.nano-editor.org/dist/v2.2/NT/nano-$NANO_VERSION.zip 
# RUN mkdir -p share/nano && unzip nano-$NANO_VERSION.zip -d share/nano && printf '#!/bin/bash \nexec /share/nano/nano.exe "$@"' > bin/nano 
# RUN chmod +x bin/nano && echo -e "Nano installed, enjoy!"
RUN apt update && apt install yum
RUN yum install nano

# Allow SMTP port to be visible
EXPOSE 25

# Start postfix server and leave the container running
CMD postfix start