FROM resin/rpi-raspbian

# RUN apt-get update && apt-get install expect
# COPY install_script /etc/postfix/install_script
# ENV DEBIAN_FRONTEND interactive
# ENTRYPOINT set -v && /etc/postfix/install_script
# EXPOSE 25
# CMD postfix start && tail -f /dev/null

# Good for debugging
RUN apt-get install -y mutt dnsutils telnet nano curl

RUN apt update && apt install debconf
ENTRYPOINT debconf-set-selections <<< "postfix postfix/mailname string $(hostname -f)" && debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
RUN apt update && apt install postfix postfix-mysql && apt install debconf
EXPOSE 25
CMD postfix start && tail -f /dev/null