FROM resin/rpi-raspbian

RUN apt-get update && apt-get install postfix

RUN apt-get install expect
ADD install_script /etc/postfix
RUN install_script

WHERE install_script is
#!/usr/bin/expect
set timeout 2
spawn "./your_script"
expect “Question 1 :” { send “yes\n” }
expect “Question 2 :” { send “no\n” }
interact

ENTRYPOINT postfix start

