FROM resin/rpi-raspbian

# RUN apt-get update && apt-get install expect
# COPY install_script /etc/postfix/install_script
# ENV DEBIAN_FRONTEND interactive
# ENTRYPOINT set -v && /etc/postfix/install_script
# EXPOSE 25
# CMD postfix start && tail -f /dev/null

# Set params for postfix install
RUN apt update && apt install debconf
# RUN debconf-set-selections <<< "postfix postfix/mailname string $(hostname -f)" 
# RUN debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
RUN echo "postfix postfix/mailname string $(hostname -f)" | debconf-set-selections
RUN echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections

# Postfix install 
RUN apt update && apt install postfix postfix-mysql

# For debuggin
RUN apt update && apt install yum
RUN yum install nano && yum install vim && 

# Allow SMTP port to be visible
EXPOSE 25

# Start postfix server and leave the container running
CMD postfix start