#!/usr/bin/expect
set timeout 2
spawn apt-get update && apt-get install postfix
expect “General type of mail configuration:” { send "2\n” }
expect “System mail name:” { send “testing-domain.grrr\n” }
interact
expect eof