#!/usr/bin/expect
set timeout 10
spawn apt-get install postfix
expect “General type of mail configuration:” { send "2\n” }
# expect “System mail name:” { send “testing-domain.grrr\n” }
expect “System mail lucy:” { send “testing-domain.grrr\n” }
interact
expect eof
wait