#!/usr/bin/expect

# set -eo pipefail
set timeout 10

# The below command is for turning back on the interactive shell when installing postfix
# export DEBIAN_FRONTEND=noninteractive
# unset $DEBIAN_FRONTEND
# env -u DEBIAN_FRONTEND

spawn sudo apt-get install postfix
# expect “General type of mail configuration:” { send "2\n” }
# expect “System mail name:” { send “raspberrypi.test\n” }
expect “General type of mail configuration: ” { send "2\n" }
expect “System mail name: ” { send "raspberrypi.test\n" }
log_file myfile.log
send_log "this is in the log file \n"
log_file
interact
expect eof
wait
exec "$@"