#!/usr/bin/expect
set timeout 10
spawn apt-get install postfix
# expect “General type of mail configuration:” { send "2\n” }
# expect “System mail name:” { send “raspberrypi.test\n” }
expect “General type of mail configuration: ” { send "2\n" }
expect “System mail name: ” { send "raspberrypi.test\n" }
interact
expect eof
wait

 >> /etc/postfix/test_log