#!/usr/bin/expect
set timeout 10
spawn apt-get install postfix
# expect “General type of mail configuration:” { send "2\n” }
# expect “System mail name:” { send “raspberrypi.test\n” }
expect “General type of mail configuration:” { send "2\r” }
expect “System mail name:” { send “raspberrypi.test\r” }
interact
expect eof
wait