#!/usr/bin/expect
set timeout 10
# export DEBIAN_FRONTEND=interactive
spawn sudo apt-get install postfix
# expect “General type of mail configuration:” { send "2\n” }
# expect “System mail name:” { send “raspberrypi.test\n” }
expect “General type of mail configuration: ” { send "2\n" }
expect “System mail name: ” { send "raspberrypi.test\n" }
log_file myfile.log
send_log "this is in the log file \n"
log_file
interact
expect eof
wait
